networks:
  imax_net: # main network between nodes
    driver: bridge

volumes:
  shared-data:

services:
  # nameserver
  nameserver:
    build: .
    container_name: nameserver
    command: python3 -m Pyro5.nameserver -n 0.0.0.0
    networks:
      - imax_net

  # worker nodes (5 workers)
  worker0:
    build: .
    container_name: worker0
    hostname: worker0
    command: python3 worker.py
    environment:
      - NODE_NAME=WORKER0
      - PYTHONUNBUFFERED=1
    networks:
      - imax_net
    volumes:
      - shared-data:/data
    depends_on:
      - nameserver
      
  worker1:
    build: .
    container_name: worker1
    hostname: worker1
    command: python3 worker.py
    environment:
      - NODE_NAME=WORKER1
      - PYTHONUNBUFFERED=1
    networks:
      - imax_net
    volumes:
      - shared-data:/data
    depends_on:
      - nameserver
    
  worker2:
    build: .
    container_name: worker2
    hostname: worker2
    command: python3 worker.py
    environment:
      - NODE_NAME=WORKER2
      - PYTHONUNBUFFERED=1
    networks:
      - imax_net
    volumes:
      - shared-data:/data
    depends_on:
      - nameserver

  worker3:
    build: .
    container_name: worker3
    hostname: worker3
    command: python3 worker.py
    environment:
      - NODE_NAME=WORKER3
      - PYTHONUNBUFFERED=1
    networks:
      - imax_net
    volumes:
      - shared-data:/data
    depends_on:
      - nameserver

  worker4:
    build: .
    container_name: worker4
    hostname: worker4
    command: python3 worker.py
    environment:
      - NODE_NAME=WORKER4
      - PYTHONUNBUFFERED=1
    networks:
      - imax_net
    volumes:
      - shared-data:/data
    depends_on:
      - nameserver

  # central server
  master:
    build: .
    container_name: master
    hostname: master
    command: python3 master.py
    environment:
      - NODE_NAME=MASTER
      - PYTHONUNBUFFERED=1
    networks:
      - imax_net
    volumes:
      - shared-data:/data
    depends_on:
      - worker0
      - worker1
      - worker2
      - worker3
      - worker4
      - nameserver